# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-21 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='contact',
            name='dob',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='contact',
            name='lastname',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
