# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-21 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20221121_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='status',
        ),
        migrations.AddField(
            model_name='contact',
            name='counter_is',
            field=models.CharField(blank=True, max_length=242, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='unique_code',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
